spring:
  datasource:
    url: jdbc:h2:./api
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
      path: /console

server:
  servlet:
    context-path: /api